#ddev-generated
# Simple template to demonstrate addon-template
services:
  ddev-n8n:
    container_name: ddev-${DDEV_SITENAME}-n8n
    hostname: ${DDEV_SITENAME}-n8n
    image: n8nio/n8n
    command: n8n start
    networks: [default, ddev_default]
    restart: "always"
    expose:
      - "5678"
    # See https://docs.n8n.io/hosting/environment-variables/environment-variables/ for more information
    # See https://docs.n8n.io/hosting/environment-variables/configuration-methods/#keeping-sensitive-data-in-separate-files for alternate secret storage
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${DDEV_HOSTNAME}
      - HTTPS_EXPOSE=443:5678
      - HTTP_EXPOSE=80:5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${SUBDOMAIN}.${DDEV_HOSTNAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DDEV_SITENAME}.${DDEV_TLD}/
      - N8N_ENDPOINT_WEBHOOK
      - N8N_ENDPOINT_WEBHOOK_TEST
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_ENCRYPTION_KEY
      - N8N_PUSH_BACKEND=websocket
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - EXECUTIONS_PROCESS=main
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=True
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_BINARY_DATA_TTL=1440
      - N8N_PAYLOAD_SIZE_MAX=100
      - N8N_METRICS=true
      - N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL=true
      - N8N_METRICS_INCLUDE_NODE_TYPE_LABEL=true
      - N8N_METRICS_INCLUDE_CREDENTIAL_TYPE_LABEL=true
      - N8N_METRICS_INCLUDE_API_ENDPOINTS=true
      - N8N_METRICS_INCLUDE_API_PATH_LABEL=true
      - N8N_METRICS_INCLUDE_API_METHOD_LABEL=true
      - N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      - N8N_HIDE_USAGE_PAGE=true
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${SUBDOMAIN}.${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    depends_on:
      - web
    links:
      - web
    volumes:
    - "./n8n/.n8n:/home/node/.n8n"
    - ".:/mnt/ddev_config"

